### ISSUE TITLE
Optimise the code by using structs

### ISSUE THREAD

**Issue by rakeshkumarnahak** [subrajeet-maharana/quiz#2]
You can export the data of the CSV file into a slice of structs instead of a two-dimensional slice of string. And also the name of the repo can be "GO quiz game".

**Comment by subrajeet-maharana** [comment]
Hey Rakesh. That's a great idea.

**Comment by rakeshkumarnahak** [comment]
Yes I know but you must change the repo name to "GO Quiz game"

**Comment by subrajeet-maharana** [comment]
Solved
